server:
  port: 8090

spring:
  data:
    mongodb:
      #    mongodb://iapi:abc123!@#@172.16.18.138:27108,iapi:abc123!@#@172.16.18.138:27109/ipaiData
      uri: mongodb://172.16.18.138:27017,172.16.18.139:27017,172.16.18.140:27017,172.16.18.141:27017,172.16.18.142:27017/iapiData

  elasticsearch:
    jest:
      uris: http://172.16.18.139:9211
      username: elastic
      password: 8XMPKeohEdmrrWbaPXtr
#      read-timeout: 40000 #读取超时
#      connection-timeout: 40000 #连接超时



# zookeeper 配置
curator:
  #重试次数
  retryCount: 5
  #重试间隔时间
  elapsedTimeMs: 5000
  # zookeeper 地址
  connectString: zoo1:2181,zoo2:2181,zoo3:2181,zoo4:2181,zoo5:2181
#  connectString: 172.16.18.131:2181
  # session 超时时间
  sessionTimeoutMs: 60000
  # 连接超时时间
  connectionTimeoutMs: 5000
  # 是否使用本地rules
  zkEnabled: true
  # 是否是测试环境
  zkTestEnabled: false
  # 分布式锁路径
  lockPath: devLock
  # 分布式锁路径
  lockTestPath: lockTest
  # 版本
  version: 1.0.0;
  # 模型节点 前缀
  zkPrefixNodePath: droolsRulesGroups
  # 模型节点 测试 前缀
  zkPrefixNodeTestPath:  droolsRulesTest
  # 节点测试规则
  zkNodeTestValue: 0
  # 系统环境变量规则
  prefixDir: drools.prefixDir


nodeCode:
  #黑名单
  blacklist: 6CD6D731CD444A4A827CF3C505E69B4E
  #发达国家
  developed: 7E250BB178D440BEE0537A1210AC57A2
  #重点上机场
  focusAir: F63ADC307A9146C2B289CA9D43E889CD
  #涉恐国家
  terrorist: 5F1450C59B8E45DF9E701EFC8CDCD83D
  #外籍华人姓氏
  fgnChName: 9EB6AD8BA21543C6A0BA915E14B882B8
  #新疆姓名
  xjName: 35A07C29B7BD44788300CF056D869E2A

