# 开发环境
spring:
  profiles:
    #指定读取配置文件:dev(开发环境),prod(生产环境),qa(测试环境)
    active: dev
#    logging:
#      config: classpath:log4j-{profiles}.properties
#      config: classpath:log4j-prod.properties




