package com.iapi.drools.rules;
import java.util.Map

dialect  "mvel"

// 外籍涉疆重点人员
rule "WJSJZDRY_1_ENTER"

    salience 10
//    agenda-group "enter_rule"
//    auto-focus true
//{C1} OR {C2} OR {C3} OR {C4} OR {C7}) AND {C5}  AND {C8} AND {C9}
    when
        $map:Map(
           (
            $map.get("ZDGZ") =="1" // C1 重点关注库掌握人员等于1
            || $map.get("QZTJ") =="1"  // C2 是否申请过团聚签证等于1
            || $map.get("XJZS") =="1" // C3 在疆内有过常住或临住记录的人员等于1
            || $map.get("XJXM") =="1" // C4 是否符合新疆姓名特点不等于0
            || $map.get("WJWZ") =="1" // C7是否外籍维族人员等于1
        )
        &&
        $map.get("GJ") !="CHN" // C5 国籍不等于CHN
        && $map.get("WHXS") =="0" // C8 外籍华人姓氏等于0
        && $map.get("ZJLX") !="11" // C9 证件类型不等于11
        )
    then
     drools.setFocus("f_rule");
     System.out.println("进入规则 ---*--外籍涉疆重点人员--*---  ");
end

// 过滤
rule "WJSJZDRY_1_FILTER"

    salience 2
    agenda-group "f_rule"
    // C6
    when
        $map:Map(["KOR","ISR","PRK","MNG"] contains $map.get("GJ")  // C6 国籍属于KOR,ISR,PRK,MNG
        )
    then
         drools.halt();
end

// 预警 黑名单 {C1}
rule "WJSJZDRY_1_HMD1"
    salience 1
    agenda-group "f_rule"
    when
        $map:Map(
        // 请李志维 确定一下 黑名单 使用的字段
            $map.get("HMD")=="1"// C1 是否黑名单人员等于1
        )
    then
//     System.out.println("请李志维 确定一下 黑名单 使用的字段");
end

// 预警 外籍维族人 {C2}
rule "WJSJZDRY_1_WJWZR"
    salience 1
    agenda-group "f_rule"

    when
        $map:Map(
            $map.get("WJWZ") =="1" // C2 是否外籍维族人员等于1
        )
    then
     System.out.println("C2 是否外籍维族人员等于1 ");
end

// 预警 重点关注 	{C3}
rule "WJSJZDRY_1_ZDGZ"
    salience 1
    agenda-group "f_rule"
    when
        $map:Map(
            $map.get("ZDGZ") =="1" // C2 是否外籍维族人员等于1
        )
    then
     System.out.println("C3重点关注库掌握人员等于1");
end

// 预警  Q类签证 {C4}
rule "WJSJZDRY_1_QLQZ"
    salience 1
    agenda-group "f_rule"
    when
        $map:Map(
            $map.get("QZTJ") =="1"  //C4是否申请过团聚签证等于1
        )
    then
     System.out.println("C4是否申请过团聚签证等于1");
end

// 预警 新疆住宿 	{C5}
rule "WJSJZDRY_1_XJZS"
    salience 1
    agenda-group "f_rule"
    when
        $map:Map(
            $map.get("XJZS") =="1"  //C5在疆内有过常住或临住记录的人员等于1
        )
    then
     System.out.println("C5在疆内有过常住或临住记录的人员等于1");
end

// 预警 维族姓名 {C6}
rule "WJSJZDRY_1_WZXM"
    salience 1
    agenda-group "f_rule"
    when
        $map:Map(
          $map.get("XJXM") =="1" //C4 是否符合新疆姓名特点不等于0  ->  C6是否符合新疆姓名特点等于1
        )
    then
     System.out.println("C6是否符合新疆姓名特点等于1");
end

// 预警 证类99 {C7}
rule "WJSJZDRY_1_ZL99"
    salience 1
    agenda-group "f_rule"
    when
        $map:Map(
          $map.get("WJWZ") =="1" // C7证件类型等于99(是否外籍维族人)
        )
    then
     System.out.println("C7证件类型等于99");
end













