package com.iapi.drools.rules;
import java.util.Map;

dialect  "mvel"

// 疑似持用伪假护照或冒用他人护照人员
//rule "YSSYWJHZ_MYTRHZ_1_ENTER"
rule "YSSYWJHZ_1_ENTER"
    salience 10
//    agenda-group "enter_rule"
//    auto-focus true

    when
//        {C1} AND {C2} AND {C3} AND {C4} AND {C5} AND {C6} AND {C7} AND {C8} AND {C9} AND {C10}
        $map: Map(
            $map.get("GJ")!="CHN" //C1 国籍不等于CHN
            ,$map.get("FGJJC")=="1" // C2 从非国籍国机场登机等于1
            ,$map.get("ZDSJ")=="1" // C3 是否重点上机地等于1
            ,$map.get("QZGJ")=="0" // C4 是否护照国籍国签发等于0
            ,["TUR","SYR","AFG","PAK","IRQ"] contains $map.get("QZQFW") //C5 外国人签证签发单位包含TUR SYR AFG PAK IRQ
            ,$map.get("QZML")=="1" // C6 当前和既往签证种类仅为M和L等于1
            ,$map.get("SCLH")=="1" //C7 是否首次来华等于1
            ,(!$map.get("NL").equals("") && $map.get("NL")!= null && Integer.parseInt($map.get("NL"))>10) //C8 年龄大于10
            ,$map.get("SJDFD")=="0" //C9 初始上机地是否为发达国家等于0
            ,$map.get("ZJLX")!="11" //C10 证件类型不等于11
        )

    then
//        System.out.println("请李志维同学确定一下 C4、C6、 指标字段和指标值 ");
        drools.setFocus("yssywjhz_mytrhz_danger");
end

// 伪造冒用护照

    rule "YSSYWJHZ_1_WZMYHZ"
    salience 1
    agenda-group "yssywjhz_mytrhz_danger"

    when
        eval(true)
        // {C1} AND {C2} AND {C3} AND {C4} AND {C5} AND {C6} AND {C7}
//         $map: Map(
//                    $map.get("country")!="CHN" //C1 国籍不等于CHN
//                    ,$map.get("FGJJC")=="1" // C2 从非国籍国机场登机等于1
//                    ,$map.get("ZDSJ")=="1" // C3 是否重点上机地等于1
//                    ,$map.get("QZGJ")=="0" // C4 是否护照国籍国签发等于0
//                    ,["TUR","SYR","AFG","PAK","IRQ"] contains $map.get("QZQFW") //C5 外国人签证签发单位包含TUR SYR AFG PAK IRQ
//                    ,$map.get("QZML")=="1" // C6 当前和既往签证种类仅为M和L等于1
//                    ,$map.get("SCLH")=="1" //C7 是否首次来华等于1
//
//                )
    then
//        System.out.println("请李志维同学确定一下 C4、C6、 指标字段和指标值 ");
        System.out.println("预警触发 ---*--伪造冒用护照--*--- 由于进入规则触发，不用再次判断预警条件");

end















