package com.iapi.drools.rules;
import java.util.Map;

dialect  "mvel"

// 疑似持用本人护照偷渡
rule "YSCYBRHZTD_1_ENTER"
//    agenda-group "enter_rule"
    salience 10
//    auto-focus true

    when
/*         {C7} AND {C6} AND {C8} AND
            (
                ({C1} AND {C2} AND {C3})
                OR
                ({C2} AND {C3} AND {C4} AND {C5})
              )
*/
         $map:Map(
            $map.get("SJDFD")=="0" // C7 初始上机地是否为发达国家等于0
            && (toInt($map.get("NL"))>10)  // C6 年龄大于10
            && $map.get("ZJLX")!="11" // C8 证件类型不等于11
            && $map.get("SCLH")=="1"  // C3 是否首次来华等于1
            && $map.get("QZML")=="1"// C2 签证种类属于M,L
            && (
                ["IRN","AFG","LKA","SYR","COG","EGY","BGD","SGP","PAK","GEO","NPL"] contains $map.get("GJ") // C1 国籍属IRN,AFG,LKA,SYR,COG,EGY,BGD,SGP,PAK,GEO,NPL
                ||(
                     ["MYS","VNM","IND","IDN","MOZ","LSO"] contains $map.get("GJ") // C4 国籍属于MYS,VNM,IND,IDN,MOZ,LSO
                  && $map.get("FGJJC")=="1" // C5 从非国籍国机场登机等于1
                )
            )
        )
    then
//        System.out.println("请李志维同学确定一下 C2 指标字段和指标值 ");
        drools.setFocus("yscybrhztd_danger");
end

// 本人护照偷渡 过滤
rule "YSCYBRHZTD_1_FILTER"
   salience 2
   agenda-group "yscybrhztd_danger"

   when
        $map: Map(
//            {C9} AND {C10}
            $map.get("GJ")=="LKA" // C9 国籍等于LKA
            && $map.get("QZQFW") =="SGPA" // C10 外国人签证签发单位等于SGPA
        )
   then
        System.out.println("过滤规则触发 删除内存中的对象");
        drools.halt();
end

// 本人护照偷渡  预警
rule "YSCYBRHZTD_1_DANGER_1"
   salience 1
   agenda-group "yscybrhztd_danger"

   when
        $map: Map(
            // {C1} AND {C2} AND {C3}
             $map.get("SCLH")=="1"  // C3 是否首次来华等于1
             && $map.get("QZML")=="1"// C2 签证种类属于M,L
             && ["IRN","AFG","LKA","SYR","COG","EGY","BGD","SGP","PAK","GEO","NPL"] contains $map.get("GJ") // C1 国籍属IRN,AFG,LKA,SYR,COG,EGY,BGD,SGP,PAK,GEO,NPL
             )
   then
//        System.out.println("请李志维同学确定一下 C2 指标字段和指标值 ");
        System.out.println("预警1规则触发 {C1} AND {C2} AND {C3}");
end


// 本人护照偷渡  预警
rule BRHZTD_1_DANGER_2
   salience 1
   agenda-group "yscybrhztd_danger"

   when
        $map: Map(
            // {C2} AND {C3} AND {C4} AND {C5}
             $map.get("SCLH")=="1"  // C3 是否首次来华等于1
             && $map.get("QZML")=="1"  // C2 签证种类属于M,L
             && ["MYS","VNM","IND","IDN","MOZ","LSO"] contains $map.get("GJ") // C4 国籍属于MYS,VNM,IND,IDN,MOZ,LSO
             && $map.get("FGJJC")=="1" // C5 从非国籍国机场登机等于1
             )
   then
//        System.out.println("请李志维同学确定一下 C2 指标字段和指标值 ");
        System.out.println("预警2规则触发 {C2} AND {C3} AND {C4} AND {C5}");
end
























