package com.iapi.drools.rules;

import java.util.Map

dialect  "mvel"

// LKA过境偷渡
rule "LKA_1_ENTER"
//    agenda-group "enter_rule"
//    auto-focus true
    salience 10

    when
        $map:Map(
            //{C1} AND {C2} AND {C3} AND {C4}
            $map.get("GJ") == "LKA" // C1 国籍等于LKA
             && $map.get("ZZXJD") != "CHN" // C2 最终下机地国家不等于CHN
             && $map.get("ZJLX") !="11" // C3 证件类型不等于11
             && $map.get("SJDFD") =="0" // C4 初始上机地是否为发达国家等于0
        )
    then
        System.out.println("进入规则触发  LKA过境偷渡");
        drools.setFocus("lka_danger");
end

// 	LKA过境偷渡
rule LKA_1_LKAGJTD
    agenda-group "lka_danger"
    salience 1
    when
        eval(true)
        // 进入规则触发了，说明国籍必然是lka ，直接预警规则触发不用再次匹配
//        $map.get("country") == "LKA" // C1 国籍等于LKA
    then
        System.out.println("预警规则触发  LKA过境偷渡");
end




